export interface Molecule {
  name: string;
  formule: string;
}

export const listeMolecules: Molecule[] = [
  { name: "Dihydrogène", formule: "H2" },
  { name: "Dioxygène", formule: "O2" },
  { name: "Diazote", formule: "N2" },
  { name: "Dioxyde de carbone", formule: "CO2" },
  { name: "Monoxyde de carbone", formule: "CO" },
  { name: "Ozone", formule: "O3" },
  { name: "Dichlore", formule: "Cl2" },
  { name: "Dibrome", formule: "Br2" },
  { name: "Diiode", formule: "I2" },
  { name: "Fluor", formule: "F2" },
  { name: "Hélium", formule: "He" },
  { name: "Argon", formule: "Ar" },
  { name: "Ammoniac", formule: "NH3" },
  { name: "Protoxyde d’azote", formule: "N2O" },
  { name: "Dioxyde d’azote", formule: "NO2" },
  { name: "Eau", formule: "H2O" },
  { name: "Eau oxygénée (peroxyde d'hydrogène)", formule: "H2O2" },
  { name: "Acide chlorhydrique", formule: "HCl" },
  { name: "Acide sulfurique", formule: "H2SO4" },
  { name: "Acide nitrique", formule: "HNO3" },
  { name: "Acide phosphorique", formule: "H3PO4" },
  { name: "Acide acétique (éthanoïque)", formule: "CH3COOH" },
  { name: "Acide benzoïque", formule: "C6H5COOH" },
  { name: "Acide formique (méthanoïque)", formule: "HCOOH" },
  { name: "Acide citrique", formule: "C6H8O7" },
  { name: "Méthanol", formule: "CH3OH" },
  { name: "Éthanol", formule: "C2H5OH" },
  { name: "Propanol", formule: "C3H7OH" },
  { name: "Butanol", formule: "C4H9OH" },
  { name: "Glycérol", formule: "C3H8O3" },
  { name: "Méthane", formule: "CH4" },
  { name: "Éthane", formule: "C2H6" },
  { name: "Propane", formule: "C3H8" },
  { name: "Butane", formule: "C4H10" },
  { name: "Pentane", formule: "C5H12" },
  { name: "Hexane", formule: "C6H14" },
  { name: "Benzène", formule: "C6H6" },
  { name: "Toluène", formule: "C7H8" },
  { name: "Glucose", formule: "C6H12O6" },
  { name: "Saccharose (sucre)", formule: "C12H22O11" },
  { name: "Fructose", formule: "C6H12O6" },
  { name: "Chlorure de sodium", formule: "NaCl" },
  { name: "Hydroxyde de sodium (soude)", formule: "NaOH" },
  { name: "Hydroxyde de potassium", formule: "KOH" },
  { name: "Carbonate de calcium", formule: "CaCO3" },
  { name: "Sulfate de cuivre", formule: "CuSO4" },
];
